### ISSUE TITLE
library called `ze` keeps giving error.

### ISSUE THREAD

**Issue by RunqiuBao** [uzh-rpg/rpg_esim#6] opened 2018-11-12 02:56 UTC
Hi, what is this library called `ze`? Does it have similar functions as eigen?
It keeps giving me error.
![image](https://user-images.githubusercontent.com/35663368/48323892-bbb9a980-e671-11e8-8420-d5ea43c02285.png)

**Comment by supitalp** [comment] 2018-11-13 07:54
Hi, `ze` is a set of useful functions provided by https://github.com/uzh-rpg/ze_oss
What error do you have exactly? On which system?

**Comment by supitalp** [comment] 2018-12-06 08:46
Hello,
Did you resolve this problem? If not, could you please give me a bit more information about it (which error do you have exactly, which system, version of ROS, CMake and gcc?
Thanks.

**Comment by supitalp** [comment] 2019-03-22 11:34
Hi,
Since you did not reply, I assume the problem is fixed and will close this issue.

**Closed by supitalp** 2019-03-22 11:34 UTC
